### ISSUE TITLE
运行ch12 单目稠密建图的程序时出现段错误（核心已转储）

### ISSUE THREAD

**Issue by Tangyy12** [gaoxiang12/slambook2#178]
运行如下：
read total 202 files.
*** loop 1 ***
段错误 (核心已转储)
用gdb调试以后定位如下：
#0  0x0000555555559715 in epipolarSearch(cv::Mat const&, cv::Mat const&, Sophus::SE3<double, 0> const&, Eigen::Matrix<double, 2, 1, 0, 2, 1> const&, double const&, double const&, Eigen::Matrix<double, 2, 1, 0, 2, 1>&, Eigen::Matrix<double, 2, 1, 0, 2, 1>&) ()
#1  0x000055555555afce in update(cv::Mat const&, cv::Mat const&, Sophus::SE3<double, 0> const&, cv::Mat&, cv::Mat&) ()
#2  0x0000555555558238 in main ()
然后我就不知道该如何解决了
小白一枚，求大神指个明路！

**Comment by pengpeng7** [comment]
我也遇到了，请问您解决了吗

**Comment by Tangyy12** [comment]
没有解决呢，暂时先放弃了，等后续回头再看看吧，如果你解决了，希望可以分享一下解决方案


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaoxiang12/slambook2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaoxiang12/slambook2] 运行ch12 单目稠密建图的程序时出现段错误（核心已转储） (#178)





 
我也遇到了，请问您解决了吗

**Comment by yan99033** [comment]
锁定问题的根源了

发现了一个奇怪的bug，大家可以试一试：
在update函数里面的nested for-loop把x和y的值打印出来，你会发现outer loop的值会超出范围，所以导致出错

**Comment by solidexu** [comment]
我也遇到这个问题，通过这种方式解决了，应该是代码优化问题
https://blog.csdn.net/u012858839/article/details/123850031

**Comment by xiangxuedao** [comment]
上面的问题最终解决了吗？
小白坑求大佬帮忙解决一下，谢谢了。

**Comment by suhangsong** [comment]
> > 上面的问题最终解决了吗？ 小白坑求大佬帮忙解决一下，谢谢了。
> 
> 前面的兄弟是对的，把bool改称void就好了

就是因为缺少返回值，加上返回值，或者改为void都可以。
开O3优化后，好像缺少返回值会导致各种奇葩的错误，具体原因不懂。

**Comment by leo-frank** [comment]
把CMakeLists.txt中的-O3优化去掉就可以了

**Comment by WEEKQUEE** [comment]
不用改代码，cmakelists里debug+  -O0就对了

**Comment by HLkyss** [comment]
> update函数为定义为bool类型，但是没有返回值，可以改为void

成功解决，感谢
