### ISSUE TITLE
ch13 "run_kitti_stere" received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by ColderWANG** [gaoxiang12/slambook2#233]
运行环境：ubuntu20 
库版本：   boost1_71， opencv3.4.16， eigen3.3.4，pcl1.9.1 ，Sophus 和DBoW3 是master版本，其他库为slambook2指定版本
问题：运行ch13的 bin/run_kitti_stereo 出现段错误，经过调试发现错误
```
(gdb)
Continuing.
I0331 19:10:14.629669 27189 backend.cpp:163] Outlier/Inlier in optimization: 0/2212

Thread 3 "run_kitti_stere" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe65fb700 (LWP 27190)]
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:96
96      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
```
想请教一下各位大佬，怎么解决这个问题

**Comment by ColderWANG** [comment]
添加
```
(gdb) backtrace
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:96
#1  0x00007ffff47119c1 in xkb_keymap_new_from_string () at /lib/x86_64-linux-gnu/libxkbcommon.so.0
#2  0x00007ffff7dbf1ef in pangolin::wayland::keyboard_handle_keymap(void*, wl_keyboard*, unsigned int, int, unsigned int) () at /usr/local/lib/libpangolin.so
#3  0x00007ffff18f1ff5 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#4  0x00007ffff18f140a in  () at /lib/x86_64-linux-gnu/libffi.so.7
#5  0x00007ffff474d3a8 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#6  0x00007ffff4749c48 in  () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#7  0x00007ffff474b21c in wl_display_dispatch_queue_pending () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#8  0x00007ffff474b67f in wl_display_roundtrip_queue () at /lib/x86_64-linux-gnu/libwayland-client.so.0
#9  0x00007ffff7d08ed2 in pangolin::FinishFrame() () at /usr/local/lib/libpangolin.so
#10 0x00007ffff7f3383e in myslam::Viewer::ThreadLoop() (this=0x55555557c300) at /home/w/Workspace/slambook2/ch13/src/viewer.cpp:73
#11 0x00007ffff7a52de4 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff7678609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#13 0x00007ffff788c163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by karthikbolla** [comment]
Did you solved the issue?
